const products_and_services = [
	{
		productId: "1",
		productLogo: "https://bryandoconnor.s3-us-west-2.amazonaws.com/images/Branding-icon.svg",
		productLogoAlt: "Marketing Package Logo",
		productName: "Marketing Package",
		productColor: "#e12345",
		productRowHeader: "This package includes logo, business card, envelope & letterhead designs as well as a style guide!",
		productCardHeader: "Professional Brand & Marketing Solutions!",
		productIncludes1: "✓ Logo Design",
		productIncludes2: "✓ Business Card Design",
		productIncludes3: "✓ Style Guide",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$14,999.99"
	},
	{
		productId: "2",
		productLogo: "https://bryandoconnor.s3-us-west-2.amazonaws.com/images/Logos-icon.svg",
		productLogoAlt: "Logo Design Logo",
		productName: "Logo Design",
		productColor: "#ae3ae3",
		productRowHeader: "Logo design includes 4 logo versions. 10 thumbnails, 2 revisions, 3 roughs, and 1 final world-class logo!",
		productCardHeader: "Outstanding Logo Creation & Design",
		productIncludes1: "✓ Refresh or Recreate a Logo",
		productIncludes2: "✓ Professional Look",
		productIncludes3: "✓ Vector Files",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$9,999.99"
	},
	{
		productId: "3",
		productLogo: "https://bryandoconnor.s3-us-west-2.amazonaws.com/images/BusinessCards-icon.svg",
		productLogoAlt: "Business Card Design Logo",
		productName: "Business Card Design",
		productColor: "#ffbb00",
		productRowHeader: "Your business card design includes 3 layout roughs, one final layout and file formats for future use (print and vector)!",
		productCardHeader: "Expert Business Card Layout & Design",
		productIncludes1: "✓ Beautiful Custom Designs",
		productIncludes2: "✓ Professional Templates",
		productIncludes3: "✓ Print-ready Files",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$499.99"
	},
	{
		productId: "4",
		productLogo: "https://bryandoconnor.s3-us-west-2.amazonaws.com/images/Illustrations-icon.svg",
		productLogoAlt: "Custom Illustrations Logo",
		productName: "Custom Illustrations",
		productColor: "#ffe600",
		productRowHeader: "Your custom illustration includes 3 layout roughs, one final layout and file formats for future use (print only)!",
		productCardHeader: "Create Your Vision With a Custom Illustration",
		productIncludes1: "✓ Professional Illustration",
		productIncludes2: "✓ Choose Style and Color Options",
		productIncludes3: "✓ Print-ready Files",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$8,999.99"
	},
	{
		productId: "5",
		productLogo: "https://bryandoconnor.s3-us-west-2.amazonaws.com/images/Invites-icon.svg",
		productLogoAlt: "Wedding Invite Design Logo",
		productName: "Wedding Invite Design",
		productColor: "#26ff00",
		productRowHeader: "Custom wedding invite design includes 3 layout roughs, one final layout and file formats that last a lifetime!",
		productCardHeader: "Beautiful Custom Wedding Invites",
		productIncludes1: "✓ Create Your Dream Invite",
		productIncludes2: "✓ Professional Template",
		productIncludes3: "✓ Print-ready Files",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$399.99"
	},
	{
		productId: "6",
		productLogo: "https://bryandoconnor.s3-us-west-2.amazonaws.com/images/Web-icon.svg",
		productLogoAlt: "Website Design Logo",
		productName: "Website Design",
		productColor: "#00ffee",
		productRowHeader: "Your professional website design includes a SPA with 5 pages, 10 hand-picked images, and modern iconography!",
		productCardHeader: "Professional Small Business Website",
		productIncludes1: "✓ Fully Functioning Code",
		productIncludes2: "✓ Professional UX/UI",
		productIncludes3: "✓ Amazing Images and Icons",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$19,999.99"
	}
];

export default products_and_services;